FROM sonarqube:9.7-community

ADD https://github.com/amalabey/sonar-external-analyzer/releases/download/release-0.0.5/sonar-external-analyzer-0.0.5.jar /opt/sonarqube/extensions/plugins/
ADD https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/3.0.1/sonar-dependency-check-plugin-3.0.1.jar /opt/sonarqube/extensions/plugins/