version: "3.8"
services:
  app:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - .zshrc:/root/.zshrc
    command: sleep infinity
    network_mode: service:sonarqube

  sonarqube:
    image: sonarqube:9.7-community
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"

  dtrack-apiserver:
    image: dependencytrack/apiserver:4.6.0
    deploy:
      resources:
        limits:
          memory: 8192m
      restart_policy:
        condition: on-failure
    ports:
      - "8081:8080"
    volumes:
      - "dependency_track:/data"
    restart: unless-stopped

  dtrack-frontend:
    image: dependencytrack/frontend:4.6.0
    depends_on:
      - dtrack-apiserver
    environment:
      - API_BASE_URL=http://localhost:8081
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  dependency_track:
