version: "3.8"
services:
  app:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - ..:/workspace:cached
      - .zshrc:/root/.zshrc
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    network_mode: service:sonarqube

  sonarqube:
    image: sonarqube:9.7-community
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  dependency_track:
